---
title: "Observable Plots"
format: html
---

```{r}
#| include: false
source('R/setup.R')

# Run clean-tabular.R if processed folder doesn't exist (needed for OJS plots)
# processed_dir <- file.path(output_dir, "tabular", "processed")
# if (!dir.exists(processed_dir) || length(list.files(processed_dir)) == 0) {
#   source('R/clean-tabular.R')
# }
```

```{ojs}
d3 = require("d3@7")

import { setD3, setWidth, setCity, setCountry, plot_pga, plot_pgp, plot_pas, plot_pas_pyramid, plot_age, plot_dependency, plot_rwi_area, plot_uba_area, plot_ubaa, plot_ubap, plot_lc, plot_uddm, plot_pv_area, plot_pv_alt, plot_pv_d, plot_pv, plot_aq, plot_summer_area, plot_ndvi_area, plot_fe, plot_fu, plot_pu, plot_cu, plot_comb, plot_e, plot_s, plot_ls_area, plot_l_area, plot_fwi, plot_fwi_d } from "./ojs/plots.js"

setD3(d3)
setWidth(width)
setCity("Nouakchott")
setCountry("Mauritania")
setHeightRatio(1.25)

import { loadData } from "./ojs/dataloader.js"
d = loadData()
```

## Population

### Population Growth (Absolute)
```{ojs}
plot_pga(d.pg)
```

### Population Growth (Percent)
```{ojs}
plot_pgp(d.pg)
```

### Population Age Structure
```{ojs}
plot_pas(d.pas)
```

### Population Pyramid (Age & Sex)
```{ojs}
plot_pas_pyramid(d.pas)
```

### Age Distribution
```{ojs}
plot_age(d.pas)
```

### Dependency Ratio
```{ojs}
plot_dependency(d.pas)
```

## Economic

### Relative Wealth Index (Area)
```{ojs}
plot_rwi_area(d.rwi_area)
```

### Urban Built-up Area
```{ojs}
plot_uba_area(d.uba_area)
```

### Urban Built-up (Absolute)
```{ojs}
plot_ubaa(d.uba)
```

### Urban Built-up (Percent)
```{ojs}
plot_ubap(d.uba)
```

### Land Cover
```{ojs}
plot_lc(d.lc)
```

### Urban Density Development Matrix
```{ojs}
plot_uddm(d.pg, d.uba, d.pug)
```

## Solar

### Photovoltaic Potential (Area)
```{ojs}
plot_pv_area(d.pv_area)
```

### Photovoltaic Potential (Altitude)
```{ojs}
plot_pv_alt(d.pv)
```

### Photovoltaic Potential (Daily)
```{ojs}
plot_pv_d(d.pv)
```

### Photovoltaic Potential
```{ojs}
plot_pv(d.pv)
```

## Climate

### Air Quality
```{ojs}
plot_aq(d.aq_area)
```

### Summer Land Surface Temperature
```{ojs}
plot_summer_area(d.summer_area)
```

### NDVI (Vegetation Index)
```{ojs}
plot_ndvi_area(d.ndvi_area)
```

## Flooding

### Flood Events
```{ojs}
plot_fe(d.fe)
```

### Fluvial (River) Flooding
```{ojs}
plot_fu(d.fu)
```

### Pluvial (Rain) Flooding
```{ojs}
plot_pu(d.pu)
```

### Coastal Flooding
```{ojs}
plot_cu(d.cu)
```

### Combined Flooding
```{ojs}
plot_comb(d.comb, d.pu, d.fu, d.cu)
```

## Seismic

### Elevation
```{ojs}
plot_e(d.e)
```

### Slope
```{ojs}
plot_s(d.s)
```

### Landslide Risk (Area)
```{ojs}
plot_ls_area(d.ls_area)
```

### Liquefaction Risk (Area)
```{ojs}
plot_l_area(d.l_area)
```

## Fire

### Fire Weather Index
```{ojs}
plot_fwi(d.fwi)
```

### Fire Weather Index (Daily)
```{ojs}
plot_fwi_d(d.fwi)
```
