"""
Generate missing tabular files for local city processing

This script creates missing CSV/YML files that are normally generated by the backend
Run this from the city directory (e.g., mnt/2025-10-senegal-dakar/)
"""

import os
import sys
import yaml
import pandas as pd
import geopandas as gpd
import rasterio
import numpy as np
from pathlib import Path

def generate_demographics_summary(city_name_l, process_output_dir):
    """Generate demographics_summary.yml from demographics.csv"""
    print(f"\n📊 Generating {city_name_l}_demographics_summary.yml...")

    tabular_dir = os.path.join(process_output_dir, 'tabular')
    demographics_csv = os.path.join(tabular_dir, f'{city_name_l}_demographics.csv')

    if not os.path.exists(demographics_csv):
        print(f"   ⚠️  {city_name_l}_demographics.csv not found. Skipping demographics_summary.")
        return

    # Read demographics data
    df = pd.read_csv(demographics_csv)

    # Calculate summary statistics
    pop_dist = df.groupby(['Age_Bracket', 'Sex'])['Count'].sum().reset_index()
    total_pop = pop_dist['Count'].sum()
    pop_dist['Percentage'] = (pop_dist['Count'] / total_pop * 100)

    # Calculate sexed percentages
    male_total = pop_dist[pop_dist['Sex'] == 'm']['Count'].sum()
    female_total = pop_dist[pop_dist['Sex'] == 'f']['Count'].sum()

    pop_dist['Sexed_Percent'] = pop_dist.apply(
        lambda row: (row['Count'] / male_total * 100) if row['Sex'] == 'm'
                    else (row['Count'] / female_total * 100),
        axis=1
    )

    # Calculate key demographics
    under5 = pop_dist[pop_dist['Age_Bracket'] == '0-4']['Percentage'].sum()
    youth = pop_dist[pop_dist['Age_Bracket'].isin(['15-19', '20-24'])]['Percentage'].sum()
    working_age_brackets = ['15-19','20-24','25-29','30-34','35-39','40-44','45-49','50-54','55-59','60-64']
    working_age = pop_dist[pop_dist['Age_Bracket'].isin(working_age_brackets)]['Percentage'].sum()
    elderly = pop_dist[pop_dist['Age_Bracket'].isin(['60-64', '65-69', '70-74', '75-79', '80+'])]['Percentage'].sum()

    male_count = pop_dist[pop_dist['Sex'] == 'm']['Count'].sum()
    female_count = pop_dist[pop_dist['Sex'] == 'f']['Count'].sum()
    sex_ratio = male_count / female_count * 100 if female_count > 0 else 0

    reproductive_age = pop_dist[
        (pop_dist['Sex'] == 'f') &
        (pop_dist['Age_Bracket'].isin(['15-19', '20-24', '25-29', '30-34', '35-39', '40-44', '45-49']))
    ]['Sexed_Percent'].sum()

    summary_data = {
        'under5': f"{under5:.2f}%",
        'youth (15-24)': f"{youth:.2f}%",
        'working_age (15-64)': f"{working_age:.2f}%",
        'elderly (60+)': f"{elderly:.2f}%",
        'reproductive_age, percent of women (15-49)': f"{reproductive_age:.2f}%",
        'sex_ratio': f"{round(sex_ratio, 2)} males to 100 females"
    }

    output_file = os.path.join(tabular_dir, f'{city_name_l}_demographics_summary.yml')
    with open(output_file, 'w') as f:
        yaml.dump(summary_data, f, default_flow_style=False)

    print(f"   ✅ Created {city_name_l}_demographics_summary.yml")

def generate_landcover_stats(city_name_l, process_output_dir):
    """Generate lc.csv and lc_stats.yml from land cover raster"""
    print(f"\n🌍 Generating land cover statistics...")

    spatial_dir = os.path.join(process_output_dir, 'spatial')
    tabular_dir = os.path.join(process_output_dir, 'tabular')

    # Find land cover file
    lc_files = [f for f in os.listdir(spatial_dir) if f.endswith('_lc.tif')]
    if not lc_files:
        print(f"   ⚠️  No land cover file found. Skipping lc stats.")
        return

    lc_file = os.path.join(spatial_dir, lc_files[0])
    print(f"   📂 Reading {lc_files[0]}...")

    # Land cover class mapping
    class_values = {
        10: 'Tree cover',
        20: 'Shrubland',
        30: 'Grassland',
        40: 'Cropland',
        50: 'Built-up',
        60: 'Bare / sparse vegetation',
        70: 'Snow and ice',
        80: 'Permanent water bodies',
        90: 'Herbaceous wetland',
        95: 'Mangroves',
        100: 'Moss and lichen'
    }

    # Read raster and calculate histogram
    with rasterio.open(lc_file) as src:
        data = src.read(1)
        unique, counts = np.unique(data[data > 0], return_counts=True)

    # Create counts dictionary
    counts_dict = {}
    for class_val in class_values:
        class_name = class_values[class_val]
        idx = np.where(unique == class_val)[0]
        count = int(counts[idx[0]]) if len(idx) > 0 else 0
        if count > 0:
            counts_dict[class_name] = count

    # Write lc.csv
    lc_csv = os.path.join(tabular_dir, f'{city_name_l}_lc.csv')
    with open(lc_csv, 'w') as f:
        f.write('Land Cover Type,Pixel Count\n')
        for class_name, count in counts_dict.items():
            f.write(f'{class_name},{count}\n')

    print(f"   ✅ Created {city_name_l}_lc.csv")

    # Calculate percentages for stats
    total_pixels = sum(counts_dict.values())
    lc_stats_df = pd.DataFrame([
        {'Land Cover Type': k, 'Pixel Count': v, 'Percentage': v/total_pixels*100}
        for k, v in counts_dict.items()
    ]).sort_values('Percentage', ascending=False)

    # Get top 3
    top3 = lc_stats_df.head(3)
    ordinals = ['first', 'second', 'third']
    lc_text_dict = {}

    for i, (idx, row) in enumerate(top3.iterrows()):
        ordinal = ordinals[i]
        text = f"The {ordinal} highest landcover value is {row['Land Cover Type']} with {row['Percentage']:.2f}% of the total land area"
        if i == 0:
            text = text.replace('first ', '')
        lc_text_dict[ordinal] = text

    # Write lc_stats.yml
    lc_stats_yml = os.path.join(tabular_dir, f'{city_name_l}_lc_stats.yml')
    with open(lc_stats_yml, 'w') as f:
        yaml.dump(lc_text_dict, f, default_flow_style=False)

    print(f"   ✅ Created {city_name_l}_lc_stats.yml")

def generate_flood_stats(city_name_l, process_output_dir):
    """Generate flood statistics CSVs from flood rasters"""
    print(f"\n🌊 Generating flood statistics...")

    spatial_dir = os.path.join(process_output_dir, 'spatial')
    tabular_dir = os.path.join(process_output_dir, 'tabular')

    # Check for flood files
    flood_types = ['fluvial', 'pluvial', 'coastal', 'comb']
    available_floods = []

    for ft in flood_types:
        flood_files = [f for f in os.listdir(spatial_dir) if ft in f and f.endswith('_2020.tif')]
        if flood_files:
            available_floods.append(ft)

    if not available_floods:
        print(f"   ⚠️  No flood files found. Skipping flood stats.")
        return

    print(f"   📂 Found flood types: {', '.join(available_floods)}")

    # Check for required assets
    wsf_file = os.path.join(spatial_dir, f'{city_name_l}_wsf_evolution_utm.tif')
    pop_file = os.path.join(spatial_dir, f'{city_name_l}_population.tif')
    road_file = os.path.join(spatial_dir, f'{city_name_l}_major_roads.gpkg')

    wsf_exists = os.path.exists(wsf_file)
    pop_exists = os.path.exists(pop_file)
    road_exists = os.path.exists(road_file)

    print(f"   📊 Available assets: WSF={wsf_exists}, Pop={pop_exists}, Roads={road_exists}")

    # Generate WSF stats
    if wsf_exists:
        generate_flood_wsf_stats(city_name_l, spatial_dir, tabular_dir, available_floods)

    # Generate Population stats
    if pop_exists:
        generate_flood_pop_stats(city_name_l, spatial_dir, tabular_dir, available_floods)

    # Generate Road stats
    if road_exists:
        generate_flood_road_stats(city_name_l, spatial_dir, tabular_dir, available_floods)

    # Generate OSM stats (check for health, schools, etc.)
    generate_flood_osm_stats(city_name_l, spatial_dir, tabular_dir, available_floods)

def generate_flood_wsf_stats(city_name_l, spatial_dir, tabular_dir, flood_types):
    """Calculate WSF exposure to flooding"""
    print(f"   🏗️  Calculating WSF flood exposure...")

    wsf_file = os.path.join(spatial_dir, f'{city_name_l}_wsf_evolution_utm.tif')
    rows = []

    for ft in flood_types:
        # Find flood file
        flood_files = [f for f in os.listdir(spatial_dir)
                      if ft in f and f.endswith('_2020.tif') and 'utm' not in f]
        if not flood_files:
            continue

        flood_file = os.path.join(spatial_dir, flood_files[0])

        try:
            # Read WSF
            with rasterio.open(wsf_file) as wsf:
                wsf_array = wsf.read(1)
                pixel_area = abs(wsf.res[0] * wsf.res[1]) / 1e6  # sq km

                # Reproject flood to match WSF
                import rasterio.warp as warp
                with rasterio.open(flood_file) as flood_src:
                    flood_array = np.zeros(wsf_array.shape)
                    warp.reproject(
                        source=flood_src.read(1),
                        destination=flood_array,
                        src_transform=flood_src.transform,
                        src_crs=flood_src.crs,
                        dst_transform=wsf.transform,
                        dst_crs=wsf.crs,
                        resampling=warp.Resampling.nearest
                    )

                # Calculate cumulative exposure by year
                for year in range(1985, 2016):
                    exposed = np.sum((wsf_array <= year) & (wsf_array > 0) & (flood_array > 0))
                    exposed_sqkm = exposed * pixel_area
                    rows.append([year, f'{ft}_2020', exposed_sqkm])

        except Exception as e:
            print(f"      ⚠️  Error processing {ft}: {e}")

    if rows:
        df = pd.DataFrame(rows, columns=['year', 'type', 'exposed_built_up_sqkm'])
        df_pivot = df.pivot(index='year', columns='type', values='exposed_built_up_sqkm')
        output_file = os.path.join(tabular_dir, f'{city_name_l}_flood_wsf.csv')
        df_pivot.to_csv(output_file)
        print(f"      ✅ Created {city_name_l}_flood_wsf.csv")

def generate_flood_pop_stats(city_name_l, spatial_dir, tabular_dir, flood_types):
    """Calculate population exposure to flooding"""
    print(f"   👥 Calculating population flood exposure...")

    pop_file = os.path.join(spatial_dir, f'{city_name_l}_population.tif')
    rows = []

    for ft in flood_types:
        flood_files = [f for f in os.listdir(spatial_dir)
                      if ft in f and f.endswith('_2020.tif') and 'utm' not in f]
        if not flood_files:
            continue

        flood_file = os.path.join(spatial_dir, flood_files[0])

        try:
            with rasterio.open(pop_file) as pop:
                pop_array = pop.read(1)
                pop_array = np.where(pop_array < 0, np.nan, pop_array)

                # Dense population (60th percentile)
                pop60 = np.nanpercentile(pop_array, 60)
                dense_pop = (pop_array >= pop60).astype(float)

                with rasterio.open(flood_file) as flood_src:
                    # Match flood to pop grid
                    import rasterio.warp as warp
                    flood_array = np.zeros(pop_array.shape)
                    warp.reproject(
                        source=flood_src.read(1),
                        destination=flood_array,
                        src_transform=flood_src.transform,
                        src_crs=flood_src.crs,
                        dst_transform=pop.transform,
                        dst_crs=pop.crs,
                        resampling=warp.Resampling.nearest
                    )

                # Calculate exposure percentage
                total_dense = np.sum(dense_pop)
                exposed_dense = np.sum((dense_pop == 1) & (flood_array > 0))
                pct = (exposed_dense / total_dense * 100) if total_dense > 0 else 0

                rows.append([f'{ft}_2020', pct])

        except Exception as e:
            print(f"      ⚠️  Error processing {ft}: {e}")

    if rows:
        df = pd.DataFrame(rows, columns=['type', 'exposed_dense_pop_pct'])
        output_file = os.path.join(tabular_dir, f'{city_name_l}_flood_pop.csv')
        df.to_csv(output_file, index=False)
        print(f"      ✅ Created {city_name_l}_flood_pop.csv")

def generate_flood_road_stats(city_name_l, spatial_dir, tabular_dir, flood_types):
    """Calculate road exposure to flooding"""
    print(f"   🛣️  Calculating road flood exposure...")

    road_file = os.path.join(spatial_dir, f'{city_name_l}_major_roads.gpkg')
    rows = []

    try:
        roads = gpd.read_file(road_file, layer='major_roads')

        if roads.empty:
            print(f"      ⚠️  No roads found in {city_name_l}_major_roads.gpkg")
            return

        for ft in flood_types:
            flood_files = [f for f in os.listdir(spatial_dir)
                          if ft in f and f.endswith('_2020_utm.tif')]
            if not flood_files:
                continue

            flood_file = os.path.join(spatial_dir, flood_files[0])

            try:
                with rasterio.open(flood_file) as flood_src:
                    flood_data = flood_src.read(1)
                    flood_transform = flood_src.transform
                    utm_crs = flood_src.crs  # Get UTM CRS from flood raster

                    # Convert roads to UTM CRS
                    roads_utm = roads.to_crs(utm_crs)

                    # Create flood zone polygons
                    from rasterio.features import shapes
                    flood_mask = flood_data > 0
                    flood_polys = [shape for shape, val in shapes(flood_mask.astype('uint8'), transform=flood_transform) if val == 1]

                    from shapely.geometry import shape as shp_shape
                    flood_zones = gpd.GeoDataFrame(
                        geometry=[shp_shape(p) for p in flood_polys],
                        crs=utm_crs
                    )

                    # Clip roads to flood zones
                    clipped = gpd.overlay(roads_utm, flood_zones, how='intersection')

                    total_length = roads_utm.length.sum()
                    flooded_length = clipped.length.sum()
                    pct = (flooded_length / total_length * 100) if total_length > 0 else 0

                    rows.append([f'{ft}_2020', total_length, flooded_length, pct])

            except Exception as e:
                print(f"      ⚠️  Error processing {ft}: {e}")

    except Exception as e:
        print(f"      ⚠️  Error reading roads: {e}")
        return

    if rows:
        df = pd.DataFrame(rows, columns=['type', 'total_major_road_meter', 'meter_in_flood_zones', 'percentage_in_flood_zones'])
        output_file = os.path.join(tabular_dir, f'{city_name_l}_flood_road.csv')
        df.to_csv(output_file, index=False)
        print(f"      ✅ Created {city_name_l}_flood_road.csv")

def generate_flood_osm_stats(city_name_l, spatial_dir, tabular_dir, flood_types):
    """Calculate OSM POI exposure to flooding"""
    print(f"   📍 Calculating OSM flood exposure...")

    from rasterio.transform import rowcol

    # Check for OSM files
    osm_types = ['health', 'schools', 'fire', 'police']
    rows = []

    for poi_type in osm_types:
        osm_files = [f for f in os.listdir(spatial_dir)
                    if f'osm_{poi_type}' in f and f.endswith('.gpkg')]

        if not osm_files:
            continue

        osm_file = os.path.join(spatial_dir, osm_files[0])

        try:
            osm = gpd.read_file(osm_file)

            if osm.empty:
                continue

            for ft in flood_types:
                flood_files = [f for f in os.listdir(spatial_dir)
                              if ft in f and f.endswith('_2020.tif') and 'utm' not in f]
                if not flood_files:
                    continue

                flood_file = os.path.join(spatial_dir, flood_files[0])

                try:
                    with rasterio.open(flood_file) as flood_src:
                        flood_data = flood_src.read(1)
                        flood_transform = flood_src.transform

                        # Check each POI
                        in_flood = 0
                        for idx, row in osm.iterrows():
                            # Get pixel coordinates using correct rasterio method
                            row_idx, col_idx = rowcol(flood_transform, row.geometry.x, row.geometry.y)

                            # Check if in bounds and flooded
                            if (0 <= row_idx < flood_data.shape[0] and
                                0 <= col_idx < flood_data.shape[1] and
                                flood_data[row_idx, col_idx] > 0):
                                in_flood += 1

                        total = len(osm)
                        pct = (in_flood / total * 100) if total > 0 else 0
                        rows.append([poi_type, f'{ft}_2020', total, in_flood, pct])

                except Exception as e:
                    print(f"      ⚠️  Error processing {poi_type}/{ft}: {e}")

        except Exception as e:
            print(f"      ⚠️  Error reading {poi_type}: {e}")

    if rows:
        df = pd.DataFrame(rows, columns=['poi', 'type', 'total_pois', 'pois_in_flood_zone', 'percentage_in_flood_zone'])
        output_file = os.path.join(tabular_dir, f'{city_name_l}_flood_osm.csv')
        df.to_csv(output_file, index=False)
        print(f"      ✅ Created {city_name_l}_flood_osm.csv")

def main():
    """Main function to generate all missing tabular files"""
    print("=" * 70)
    print("🔧 GENERATE MISSING TABULAR FILES")
    print("=" * 70)

    # Get city info
    city_dir = os.getcwd()
    city_name = os.path.basename(city_dir)

    # Extract city name (e.g., "2025-10-senegal-dakar" -> "dakar")
    parts = city_name.split('-')
    if len(parts) >= 4:
        city_name_l = parts[3]
    else:
        print("❌ Error: Run this script from a city directory (e.g., mnt/2025-10-senegal-dakar/)")
        sys.exit(1)

    process_output_dir = os.path.join(city_dir, '02-process-output')

    if not os.path.exists(process_output_dir):
        print(f"❌ Error: {process_output_dir} not found")
        sys.exit(1)

    print(f"\n📁 City: {city_name_l}")
    print(f"📂 Directory: {city_dir}")
    print(f"📊 Output: {process_output_dir}")

    # Generate files
    generate_demographics_summary(city_name_l, process_output_dir)
    generate_landcover_stats(city_name_l, process_output_dir)
    generate_flood_stats(city_name_l, process_output_dir)

    print("\n" + "=" * 70)
    print("✅ DONE!")
    print("=" * 70)

if __name__ == '__main__':
    main()
