project:
  type: default
  pre-render: Rscript generate-index.R
  render:
    - index.qmd

engine: knitr

format:
  html:
    output-file: scan-calculation.html
    theme: [default, ../source/pagedtable-fix.scss]
    self-contained: true
